import { Button } from "@/components/ui/button";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import logo from "@/assets/logo.svg";
import { cn } from "@/lib/utils";
import { useAuth } from "@/hooks/use-auth";
import {
  ArrowRight,
  BarChart3,
  Bot,
  CalendarClock,
  Kanban,
  Menu,
  Sparkles,
  Users,
  X,
} from "lucide-react";
import { useState } from "react";
import { Link } from "react-router";

const WORKFLOW = [
  { step: "01", title: "Add or import leads", body: "CSV in, or one at a time. Thirty seconds per prospect." },
  { step: "02", title: "Get AI research", body: "Summary, pain points and a lead score — before you write a word." },
  { step: "03", title: "Reach out prepared", body: "A suggested angle based on what's actually going on." },
  { step: "04", title: "Follow up on time", body: "Scheduled reminders so no lead quietly goes cold." },
  { step: "05", title: "Close the loop", body: "Move leads to Won and see the whole picture." },
];

const FEATURES = [
  {
    icon: Sparkles,
    title: "Lead intelligence",
    body: "Every lead gets a research brief: what they do, where it hurts, and how to open the conversation.",
  },
  {
    icon: Users,
    title: "Lead management",
    body: "A CRM table that respects your time. Search, filter, bulk edit, import — no 40-column maze.",
  },
  {
    icon: Bot,
    title: "AI outreach",
    body: "Draft emails and LinkedIn messages tuned to each lead's context. Send by email in one click, or copy and log it manually — you approve every send.",
  },
  {
    icon: CalendarClock,
    title: "Smart follow-ups",
    body: "Day 3, day 7, day 14. DealFlow AI schedules the cadence, tracks what's overdue, and keeps leads from going quiet on you.",
  },
  {
    icon: Kanban,
    title: "Pipeline & campaigns",
    body: "A kanban view from New to Won, plus bulk campaigns with per-lead personalization. Drag a card, send a campaign — same data, different lens.",
  },
  {
    icon: BarChart3,
    title: "Analytics & AI assistant",
    body: "Contact rates, reply rates, conversion, and a chat assistant that answers questions about your pipeline in plain language.",
  },
];

const USE_CASES = [
  {
    who: "Freelancers",
    body: "Spend the time you used to burn on research actually talking to clients.",
  },
  {
    who: "Agencies",
    body: "Give every account lead the same disciplined follow-up machine.",
  },
  {
    who: "Startups",
    body: "First sales hires start productive on day one, not week three.",
  },
  {
    who: "Consultants",
    body: "Positioning that converts — without a marketing department behind it.",
  },
  {
    who: "Small sales teams",
    body: "One shared source of truth. Nothing falls through the cracks.",
  },
];

const PRICING = [
  {
    name: "Free",
    monthly: 0,
    yearly: 0,
    blurb: "For your first ten prospects.",
    features: ["10 leads", "5 AI generations", "Basic pipeline"],
    cta: "Start for free",
    highlight: false,
  },
  {
    name: "Starter",
    monthly: 499,
    yearly: 399,
    blurb: "For a steady solo pipeline.",
    features: [
      "100 leads",
      "Unlimited AI generation",
      "Follow-up reminders",
      "Analytics",
    ],
    cta: "Start for free",
    highlight: false,
  },
  {
    name: "Pro",
    monthly: 1499,
    yearly: 1199,
    blurb: "For serious outbound motion.",
    features: [
      "500+ leads",
      "Lead intelligence",
      "Campaigns",
      "Advanced analytics",
      "AI assistant",
    ],
    cta: "Start for free",
    highlight: true,
  },
  {
    name: "Business",
    monthly: null,
    yearly: null,
    blurb: "For teams with bigger ambitions.",
    features: [
      "Multiple users",
      "Advanced controls",
      "Integrations",
      "Priority support",
    ],
    cta: "Talk to us",
    highlight: false,
  },
];

const FAQS = [
  {
    q: "How does the AI actually work?",
    a: "DealFlow AI analyzes the details you capture — role, company, website, notes — and produces a research brief: a summary, likely pain points, opportunity signals, and a suggested sales angle. When an AI provider key is configured, briefs are generated by a large language model; otherwise DealFlow AI builds a structured estimate from your data. Either way, every brief is clearly labeled and nothing is fabricated into fake facts.",
  },
  {
    q: "Is there a limit on leads?",
    a: "The Free plan covers 10 leads. Starter covers 100, Pro covers 500+, and Business is custom. You can upgrade, downgrade, or export your data at any time.",
  },
  {
    q: "Who can see my lead data?",
    a: "Your leads live in your own workspace and are protected by authentication and per-user authorization checks on every query. Lead data is business-sensitive — we treat it that way: no selling data, no training on your content, and destructive actions always ask for confirmation.",
  },
  {
    q: "Does it replace my CRM?",
    a: "If your CRM is a spreadsheet wearing a suit, yes. DealFlow AI is deliberately lighter than enterprise CRM: it focuses on the loop that actually creates revenue — research, outreach, follow-up, pipeline — without asking you to maintain forty fields per contact.",
  },
  {
    q: "Can I actually send emails from DealFlow AI?",
    a: "Yes — and you don't need to buy a domain. Connect your Gmail (a free App Password, one minute of setup) and outreach emails go out from your own address to anyone: Gmail, Outlook, Yahoo or company inboxes. Every send is logged to the lead's thread. Prefer to stay hands-on? Compose → Copy message → paste into Gmail works with zero setup, and DealFlow AI still tracks it.",
  },
  {
    q: "Do I need my own domain to send email?",
    a: "No. Your Gmail address is a perfectly deliverable sender — connecting it makes DealFlow AI send as you, with no DNS records or purchases. A custom domain only becomes interesting later, when you want a branded sender for high-volume campaigns.",
  },
  {
    q: "What integrations are supported?",
    a: "Email delivery is live through your own Gmail or the optional Resend API. AI briefs run on OpenAI when a key is configured, with a built-in heuristic engine as fallback. Gmail, Outlook, LinkedIn and calendar sync are on the roadmap — the Integrations page in-app shows exactly what's connected.",
  },
  {
    q: "Can I cancel anytime?",
    a: "Yes. Monthly plans cancel at the end of the billing period, yearly plans are refundable in the first 14 days. Your data stays exportable regardless.",
  },
];

export default function Landing() {
  const { isAuthenticated, isLoading } = useAuth();
  const [menuOpen, setMenuOpen] = useState(false);
  const [yearly, setYearly] = useState(true);

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Nav */}
      <header className="sticky top-0 z-40 border-b border-border bg-background/90 backdrop-blur">
        <div className="mx-auto flex h-14 max-w-6xl items-center justify-between px-4 md:px-8">
          <Link to="/" className="flex items-center gap-2">
            <img src={logo} alt="DealFlow AI" className="size-7 rounded-md" />
            <span className="text-sm font-semibold tracking-tight">
              DealFlow<span className="text-muted-foreground"> AI</span>
            </span>
          </Link>
          <nav className="hidden items-center gap-6 text-sm text-muted-foreground md:flex">
            <a href="#workflow" className="transition-colors hover:text-foreground">How it works</a>
            <a href="#features" className="transition-colors hover:text-foreground">Features</a>
            <a href="#usecases" className="transition-colors hover:text-foreground">Use cases</a>
            <a href="#pricing" className="transition-colors hover:text-foreground">Pricing</a>
            <a href="#faq" className="transition-colors hover:text-foreground">FAQ</a>
          </nav>
          <div className="hidden items-center gap-2 md:flex">
            {isLoading ? null : isAuthenticated ? (
              <Button asChild size="sm">
                <Link to="/leads">
                  Open workspace <ArrowRight className="size-3.5" />
                </Link>
              </Button>
            ) : (
              <>
                <Button asChild variant="ghost" size="sm">
                  <Link to="/auth">Sign in</Link>
                </Button>
                <Button asChild size="sm">
                  <Link to="/auth">
                    Start for free <ArrowRight className="size-3.5" />
                  </Link>
                </Button>
              </>
            )}
          </div>
          <button
            type="button"
            className="flex size-9 items-center justify-center rounded-md border border-border md:hidden"
            aria-label={menuOpen ? "Close menu" : "Open menu"}
            aria-expanded={menuOpen}
            onClick={() => setMenuOpen((v) => !v)}
          >
            {menuOpen ? <X className="size-4" /> : <Menu className="size-4" />}
          </button>
        </div>
        {menuOpen && (
          <div className="border-t border-border px-4 py-4 md:hidden">
            <nav className="flex flex-col gap-3 text-sm text-muted-foreground">
              <a href="#workflow" onClick={() => setMenuOpen(false)}>How it works</a>
              <a href="#features" onClick={() => setMenuOpen(false)}>Features</a>
              <a href="#usecases" onClick={() => setMenuOpen(false)}>Use cases</a>
              <a href="#pricing" onClick={() => setMenuOpen(false)}>Pricing</a>
              <a href="#faq" onClick={() => setMenuOpen(false)}>FAQ</a>
              <Link to="/auth" onClick={() => setMenuOpen(false)} className="font-medium text-foreground">
                Start for free →
              </Link>
            </nav>
          </div>
        )}
      </header>

      {/* Hero */}
      <section className="relative mx-auto max-w-6xl px-4 pb-16 pt-16 md:px-8 md:pb-24 md:pt-24">
        <div aria-hidden className="pointer-events-none absolute inset-x-0 top-0 -z-10 mx-auto h-[320px] max-w-4xl">
          <div className="absolute left-1/4 top-8 size-64 rounded-full bg-[#e8dfc9]/60 blur-[110px]" />
        </div>
        <div className="mx-auto max-w-3xl text-center">
          <p className="label-caps mx-auto inline-flex items-center gap-1.5 rounded-full border border-border bg-card px-3 py-1 text-muted-foreground">
            AI-powered sales, without the sales team
          </p>
          <h1 className="mt-4 text-4xl font-semibold leading-[1.05] tracking-tight md:text-6xl">
            Turn leads into customers.
            <br />
            <span className="text-muted-foreground">Without hiring a salesperson.</span>
          </h1>
          <p className="mx-auto mt-5 max-w-xl text-base leading-relaxed text-muted-foreground md:text-lg">
            DealFlow AI researches your prospects, drafts the opening move, and keeps
            follow-ups on schedule — all in one simple sales workspace.
          </p>
          <div className="mt-7 flex flex-wrap items-center justify-center gap-3">
            <Button asChild size="lg" className="glow-primary h-11 bg-[#191713] px-6 text-[15px] text-[#f7f3ea] hover:bg-[#33302a]">
              <Link to="/auth">
                Start for free <ArrowRight className="size-4" />
              </Link>
            </Button>
            <Button asChild size="lg" variant="outline" className="h-11 px-6 text-[15px]">
              <a href="#demo">See how it works</a>
            </Button>
          </div>
          <p className="mt-4 text-xs text-muted-foreground">
            Free plan · No credit card · Your data stays yours
          </p>
        </div>

        {/* Dashboard preview */}
        <div id="demo" className="mt-14 md:mt-20">
          <DashboardPreview />
        </div>
      </section>

      {/* Workflow */}
      <section id="workflow" className="border-y border-border bg-sidebar/60 py-16 md:py-24">
        <div className="mx-auto max-w-6xl px-4 md:px-8">
          <SectionHeading
            kicker="The workflow"
            title="From stranger to signature, in five moves."
            body="Most CRMs help you store leads. DealFlow AI helps you actually convert them — the same loop a great salesperson runs, on rails."
          />
          <ol className="mt-10 grid gap-px overflow-hidden rounded-lg border border-border bg-border md:grid-cols-5">
            {WORKFLOW.map((w, i) => (
              <li key={w.step} className="bg-card p-5">
                <p className="tabular text-xs font-medium text-muted-foreground">
                  {w.step}
                </p>
                <p className="mt-2 text-sm font-semibold leading-snug">{w.title}</p>
                <p className="mt-1.5 text-[13px] leading-relaxed text-muted-foreground">
                  {w.body}
                </p>
                {i < WORKFLOW.length - 1 && (
                  <span aria-hidden className="mt-3 block h-px w-8 bg-foreground/20 md:hidden" />
                )}
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-16 md:py-24">
        <div className="mx-auto max-w-6xl px-4 md:px-8">
          <SectionHeading
            kicker="What's inside"
            title="A lightweight AI sales employee."
            body="Everything connects to one loop: lead → intelligence → outreach → follow-up → pipeline → conversion."
          />
          <div className="mt-10 grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">
            {FEATURES.map((f) => (
              <div key={f.title} className="bg-card p-6">
                <span className="flex size-10 items-center justify-center rounded-lg border border-border bg-secondary text-foreground">
                  <f.icon className="size-5" />
                </span>
                <p className="mt-3 text-sm font-semibold">{f.title}</p>
                <p className="mt-1.5 text-[13px] leading-relaxed text-muted-foreground">
                  {f.body}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Use cases */}
      <section id="usecases" className="border-y border-border bg-sidebar/60 py-16 md:py-24">
        <div className="mx-auto max-w-6xl px-4 md:px-8">
          <SectionHeading
            kicker="Who it's for"
            title="Built for people who sell it themselves."
          />
          <div className="mt-10 grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 lg:grid-cols-5">
            {USE_CASES.map((u) => (
              <div key={u.who} className="bg-card p-5">
                <p className="text-sm font-semibold">{u.who}</p>
                <p className="mt-1.5 text-[13px] leading-relaxed text-muted-foreground">
                  {u.body}
                </p>
              </div>
            ))}
          </div>
          <p className="mt-4 text-xs text-muted-foreground">
            Demo companies shown in-product (Nova Studio, Orbit Labs, and friends) are fictional.
          </p>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-16 md:py-24">
        <div className="mx-auto max-w-6xl px-4 md:px-8">
          <SectionHeading
            kicker="Pricing"
            title="Pays for itself on the first closed deal."
            body="Start free. Upgrade when your pipeline outgrows the spreadsheet."
          />
          <div className="mt-8 flex items-center justify-center gap-3">
            <div className="flex items-center rounded-md border border-border p-0.5">
              {(["Monthly", "Yearly"] as const).map((label) => {
                const active = (label === "Yearly") === yearly;
                return (
                  <button
                    key={label}
                    type="button"
                    aria-pressed={active}
                    onClick={() => setYearly(label === "Yearly")}
                    className={cn(
                      "cursor-pointer rounded px-3 py-1.5 text-xs font-medium transition-colors",
                      active
                        ? "bg-[#191713] text-[#f7f3ea]"
                        : "text-muted-foreground hover:text-foreground",
                    )}
                  >
                    {label}
                  </button>
                );
              })}
            </div>
            <span className="rounded-full border border-border bg-secondary px-2 py-0.5 text-[11px] font-medium text-muted-foreground">
              Save 20% annually
            </span>
          </div>
          <div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
            {PRICING.map((tier) => {
              const price = yearly ? tier.yearly : tier.monthly;
              return (
                <div
                  key={tier.name}
                  className={cn(
                    "depth-card-hover flex flex-col rounded-xl border bg-card p-5",
                    tier.highlight
                      ? "border-[#191713] shadow-[0_10px_30px_-18px_rgba(68,58,38,0.5)]"
                      : "border-border",
                  )}
                >
                  <div className="flex items-center justify-between">
                    <p className="text-sm font-semibold">{tier.name}</p>
                    {tier.highlight && (
                      <span className="rounded-full border border-[#191713]/40 bg-[#191713] px-2 py-0.5 text-[10px] font-medium text-[#f7f3ea]">
                        Popular
                      </span>
                    )}
                  </div>
                  <p className="mt-1 text-xs text-muted-foreground">{tier.blurb}</p>
                  <div className="mt-4 flex items-baseline gap-1">
                    {price === null ? (
                      <span className="text-2xl font-semibold tracking-tight">Custom</span>
                    ) : (
                      <>
                        <span className="tabular text-3xl font-semibold tracking-tight">
                          ₹{price.toLocaleString("en-IN")}
                        </span>
                        <span className="text-xs text-muted-foreground">/mo</span>
                      </>
                    )}
                  </div>
                  <ul className="mt-4 flex-1 space-y-2">
                    {tier.features.map((f) => (
                      <li key={f} className="flex items-start gap-2 text-[13px]">
                        <span
                          aria-hidden
                          className="mt-[7px] size-1 shrink-0 rounded-full bg-[#8a7d63]"
                        />
                        {f}
                      </li>
                    ))}
                  </ul>
                  <Button asChild className="mt-5" variant={tier.highlight ? "default" : "outline"}>
                    <Link to="/auth">{tier.cta}</Link>
                  </Button>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="border-t border-border bg-sidebar/60 py-16 md:py-24">
        <div className="mx-auto max-w-3xl px-4 md:px-8">
          <SectionHeading kicker="FAQ" title="Fair questions, straight answers." />
          <Accordion type="single" collapsible className="mt-8">
            {FAQS.map((f, i) => (
              <AccordionItem key={f.q} value={`item-${i}`}>
                <AccordionTrigger className="text-left text-sm font-medium">
                  {f.q}
                </AccordionTrigger>
                <AccordionContent className="text-sm leading-relaxed text-muted-foreground">
                  {f.a}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20 md:py-28">
        <div className="mx-auto max-w-6xl px-4 md:px-8">
          <div className="rounded-xl border border-[#191713] bg-[#191713] px-6 py-16 text-center text-[#f7f3ea] md:px-16">
            <p className="label-caps text-[#f7f3ea]/60">DealFlow AI</p>
            <h2 className="mx-auto mt-4 max-w-2xl text-3xl font-semibold leading-tight tracking-tight md:text-4xl">
              Your next customer could already be in your lead list.
            </h2>
            <div className="mt-7 flex flex-wrap justify-center gap-3">
              <Button asChild size="lg" className="h-11 bg-[#f7f3ea] px-6 text-[#191713] hover:bg-white">
                <Link to="/auth">
                  Start for free <ArrowRight className="size-4" />
                </Link>
              </Button>
              <Button
                asChild
                size="lg"
                variant="outline"
                className="h-11 border-[#f7f3ea]/30 bg-transparent px-6 text-[#f7f3ea] hover:bg-[#f7f3ea]/10 hover:text-[#f7f3ea]"
              >
                <Link to="/auth">Create free account</Link>
              </Button>
            </div>
            <p className="mt-4 text-xs text-[#f7f3ea]/50">
              Find the right leads. Say the right thing. Follow up at the right time.
            </p>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border py-10">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 px-4 text-xs text-muted-foreground md:flex-row md:px-8">
          <div className="flex items-center gap-2">
            <img src={logo} alt="" className="size-5 rounded" />
            <span>
              © {new Date().getFullYear()} DealFlow
              <span className="text-muted-foreground"> AI</span> — demo product
            </span>
          </div>
          <nav className="flex gap-5">
            <a href="#features">Features</a>
            <a href="#pricing">Pricing</a>
            <Link to="/auth">Sign in</Link>
          </nav>
        </div>
      </footer>
    </div>
  );
}

function SectionHeading({
  kicker,
  title,
  body,
}: {
  kicker: string;
  title: string;
  body?: string;
}) {
  return (
    <div className="max-w-2xl">
      <p className="label-caps text-muted-foreground">{kicker}</p>
      <h2 className="mt-3 text-2xl font-semibold tracking-tight md:text-3xl">
        {title}
      </h2>
      {body && (
        <p className="mt-3 text-[15px] leading-relaxed text-muted-foreground">{body}</p>
      )}
    </div>
  );
}

/** Static, hand-crafted replica of the actual /leads screen — not a stock graphic. */
function DashboardPreview() {
  return (
    <div className="depth-card overflow-hidden rounded-xl border border-border bg-card shadow-[0_32px_90px_-30px_rgba(0,0,0,0.65)]">
      {/* window chrome */}
      <div className="flex h-10 items-center gap-1.5 border-b border-border bg-sidebar px-4">
        <span className="size-2.5 rounded-full border border-border bg-background" />
        <span className="size-2.5 rounded-full border border-border bg-background" />
        <span className="size-2.5 rounded-full border border-border bg-background" />
        <div className="mx-auto flex h-6 w-72 items-center justify-center rounded-md border border-border bg-background text-[10px] text-muted-foreground">
          dealflow.ai/leads
        </div>
      </div>
      <div className="grid md:grid-cols-[13rem_1fr_18rem]">
        {/* mini sidebar */}
        <div className="hidden border-r border-border bg-sidebar p-3 md:block">
          <div className="flex items-center gap-2 px-1.5 pb-4">
            <img src={logo} alt="" className="size-5 rounded" />
            <span className="text-xs font-semibold">
              DealFlow<span className="text-muted-foreground"> AI</span>
            </span>
          </div>
          {["Leads", "Pipeline", "Campaigns", "Inbox", "Tasks"].map((item, i) => (
            <div
              key={item}
              className={cn(
                "mb-0.5 flex items-center gap-2 rounded px-2 py-1.5 text-[11px]",
                i === 0
                  ? "nav-pill-active font-medium"
                  : "text-muted-foreground/70",
              )}
            >
              <span className="size-1.5 rounded-full border border-current opacity-50" />
              {item}
            </div>
          ))}
        </div>

        {/* mini lead table */}
        <div className="min-w-0 border-r border-border">
          <div className="flex items-center justify-between border-b border-border px-4 py-2.5">
            <span className="text-xs font-semibold">Leads</span>
            <span className="rounded bg-[#191713] px-1.5 py-0.5 text-[10px] font-medium text-[#f7f3ea]">
              + Add lead
            </span>
          </div>
          <div>
            {[
              { n: "Sarah Mitchell", c: "Nova Studio", s: "Interested", cls: "border border-border bg-[#ece6d8] text-[#443f36]", sc: "87" },
              { n: "Priya Raman", c: "Elevate Commerce", s: "Meeting", cls: "border border-[#191713]/30 bg-[#191713] text-[#f7f3ea]", sc: "92" },
              { n: "Daniel Osei", c: "Northstar Digital", s: "Replied", cls: "border border-border bg-[#e9e2d2] text-[#443f36]", sc: "81" },
              { n: "Elena Vasquez", c: "Orbit Labs", s: "New", cls: "border border-border bg-card text-muted-foreground", sc: "78" },
              { n: "Tom Alvarez", c: "PixelCraft", s: "New", cls: "border border-border bg-card text-muted-foreground", sc: "71" },
            ].map((r) => (
              <div
                key={r.n}
                className="flex items-center gap-3 border-b border-border/60 px-4 py-2.5 last:border-b-0"
              >
                <span className="flex size-6 items-center justify-center rounded-full border border-border bg-muted text-[9px] font-semibold text-muted-foreground">
                  {r.n.split(" ").map((p) => p[0]).join("")}
                </span>
                <div className="min-w-0 flex-1">
                  <p className="truncate text-[11px] font-medium">{r.n}</p>
                  <p className="truncate text-[10px] text-muted-foreground">{r.c}</p>
                </div>
                <span className={cn("rounded-full px-1.5 py-0.5 text-[9px] font-medium", r.cls)}>
                  {r.s}
                </span>
                <span className="tabular text-[11px] font-medium">{r.sc}</span>
              </div>
            ))}
          </div>
        </div>

        {/* mini intelligence panel */}
        <div className="hidden bg-sidebar/50 p-4 md:block">
          <p className="label-caps text-muted-foreground/70">Lead intelligence</p>
          <p className="mt-2 text-xs font-semibold">Sarah Mitchell</p>
          <p className="text-[10px] text-muted-foreground">Founder @ Nova Studio</p>
          <div className="mt-3 flex items-baseline gap-1.5">
            <span className="tabular text-2xl font-semibold">87</span>
            <span className="text-[10px] text-muted-foreground">/100</span>
          </div>
          <div className="mt-2 space-y-1.5">
            {[
              ["Company fit", 90],
              ["Industry fit", 85],
              ["Engagement", 92],
            ].map(([label, value]) => (
              <div key={label as string} className="flex items-center gap-2">
                <span className="w-16 text-[9px] text-muted-foreground">{label}</span>
                <div className="h-1 flex-1 overflow-hidden rounded-full bg-[#e4dcc9]">
                  <div className="h-full rounded-full bg-[#191713]" style={{ width: `${value}%` }} />
                </div>
              </div>
            ))}
          </div>
          <div className="mt-3 rounded-md border border-border bg-[#ece6d8] p-2">
            <p className="text-[9px] font-medium text-[#443f36]">Pain point</p>
            <p className="mt-0.5 text-[10px] leading-snug text-muted-foreground">
              Their current website experience may limit conversion from paid traffic.
            </p>
          </div>
          <div className="mt-3 flex gap-1">
            <span className="rounded bg-[#191713] px-1.5 py-1 text-[9px] font-medium text-[#f7f3ea]">
              Generate outreach
            </span>
            <span className="rounded border border-border px-1.5 py-1 text-[9px] text-muted-foreground">
              Follow-up
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
